### ISSUE TITLE
Would it be possible to change name stampede to something more unique and easy to search?

### ISSUE THREAD

**Issue by xet7** [bashovski/stampede#1]
Hi,
would it be possible to change name stampede to something more unique and easy to search?

For Stampede, I think of ToroDB Stampede:
- https://github.com/torodb/stampede/
- https://www.torodb.com

And google searches for Stampede shows many results of something not related to your project.

**Comment by xet7** [comment]
Although, it seems Deno projects are usually named with something similar, so maybe this a bad idea.

**Comment by bashovski** [comment]
Thank you for opening this issue. As Stampede has just got released this week, I believe it won't be at the top of search engines' results for certain time period. In the next couple of days, I'll release a site with the entire documentation of the project and some decent tips and tutorials to help new users increase their productivity and also help them use the framework the right way. 

I chose this name primarily so the project has some sort of correlation to Deno, nothing else.
